project_id = "ilpbkhrtbhbfcfbwvmyz"

[functions.detect-ip]
verify_jwt = false

[functions.account-health-check]
verify_jwt = false

[functions.admin-unlock-account]
verify_jwt = false

[functions.secure-login]
verify_jwt = false